push to test Co-authored-by: Max Ole Elliger <ole.elliger@fau.de> Co-authored-by: Omar Ninach <omar.ninach@fau.de>

diff --git a/.github/workflows/demo-pipeline.yaml b/.github/workflows/demo-pipeline.yaml
--- a/.github/workflows/demo-pipeline.yaml
+++ b/.github/workflows/demo-pipeline.yaml
@@ -20,7 +20,14 @@ jobs:
           pip install pylint pytest
       - name: Lint with pylint
         run: |
-          python lint.py
-      # - name: Run pytest suite
+          pylint_result=$(pylint res/mdh_extraction.py --output-format=parseable)
+          echo "$pylint_result"
+          if [[ $pylint_result =~ "rated at 10.00/10" ]]; then
+            echo "Linting passed!"
+          else
+            echo "Linting failed!"
+            exit 1
+          fi      # - name: Run pytest suite
       #   run: |
       #     pytest pytest_test.py
+
